import "./index.scss"
export { default as Hero } from "./Hero/"
export { default as Statistics } from "./Statistics/"
export { default as VideosTypes } from "./VideosType/"
export { default as TopVideos } from "./TopVideos/"
export { default as Reviews } from "./Reviews"
